/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/gallery'
    | '/sitemap.xml'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/gallery'
    | '/sitemap.xml'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clients'
    | '/gallery'
    | '/sitemap.xml'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientsRoute: typeof ClientsRoute
  GalleryRoute: typeof GalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientsRoute: ClientsRoute,
  GalleryRoute: GalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
